### ISSUE TITLE
WeekView times with double digits 

### ISSUE THREAD

**Issue by Freddymaepa** [just-imagine/Calendar#3]
In the WeekView, after having made a booking, the bookings past 9, that would be bookings that start from 10 to 18 and have double digits, they show the second digit only for 10:15 - 10:30, it shows 0:15-0:30., @phantom820 , @JusticeShai, @rootRiddick, @bafo706

**Comment by phantom820** [comment]
@Freddymaepa  That bug has been fixed and it is displaying as expected.
